const { color } = require('../lib/color')
const moment = require("moment-timezone")
let levelling = require('../lib/levelling')
const canvacord = require("canvacord")
let fetch = require("node-fetch");

module.exports = {
	async before(m) {
		let user = global.db.data.users[m.sender]
		let { min, xp, max } = levelling.xpRange(user.level, global.multiplier)
		let ppUrl = await conn.profilePictureUrl(m.sender, 'image').catch((_) => "https://telegra.ph/file/0a70ee52eb457fbcc2b92.jpg");
        let pp = await (await fetch(ppUrl)).buffer();
        let curr = user.exp - min
        let minxp = max - user.exp
		if (!user.autolevelup) return !0
		let before = user.level * 1
		while (levelling.canLevelUp(user.level, user.exp, global.multiplier)) user.level++
			if (user.level <= 1) {
		user.role = 'Warior I ★1'
	} else if (user.level <= 2) {
		user.role = 'Warior I ★2'
	} else if (user.level <= 3) {
		user.role = 'Warior I ★3'
	} else if (user.level <= 8) {
		user.role = 'Warior II ★1'
	} else if (user.level <= 10) {
		user.role = 'Warior II ★2'
	} else if (user.level <= 12) {
		user.role = 'Warior II ★3'
	} else if (user.level <= 14) {
		user.role = 'Warior III ★1'
	} else if (user.level <= 16) {
		user.role = 'Warior III ★2'
	} else if (user.level <= 18) {
		user.role = 'Warior III ★3'
	} else if (user.level <= 20) {
		user.role = 'Elite I ★1'
	} else if (user.level <= 22) {
		user.role = 'Elite I ★2'
	} else if (user.level <= 24) {
		user.role = 'Elite I ★3'
	} else if (user.level <= 26) {
		user.role = 'Elite I ★4'
	} else if (user.level <= 28) {
		user.role = 'Elite II ★1'
	} else if (user.level <= 30) {
		user.role = 'Elite II ★2'
	} else if (user.level <= 32) {
		user.role = 'Elite II ★3'
	} else if (user.level <= 34) {
		user.role = 'Elite II ★4'
	} else if (user.level <= 36) {
		user.role = 'Elite III ★1'
	} else if (user.level <= 38) {
		user.role = 'Elite III ★2'
	} else if (user.level <= 40) {
		user.role = 'Elite III ★3'
	} else if (user.level <= 42) {
		user.role = 'Elite III ★4'
	} else if (user.level <= 44) {
		user.role = 'Elite IIII ★1'
	} else if (user.level <= 46) {
		user.role = 'Elite IIII ★2'
	} else if (user.level <= 48) {
		user.role = 'Elite IIII ★3'
	} else if (user.level <= 50) {
		user.role = 'Elite IIII ★4'
	} else if (user.level <= 52) {
		user.role = 'Master I ★1'
	} else if (user.level <= 54) {
		user.role = 'Master I ★2'
	} else if (user.level <= 56) {
		user.role = 'Master I ★3'
	} else if (user.level <= 58) {
		user.role = 'Master I ★4'
	} else if (user.level <= 60) {
		user.role = 'Master I ★5'
	} else if (user.level <= 62) {
		user.role = 'Master II ★1'
	} else if (user.level <= 64) {
		user.role = 'Master II ★2'
	} else if (user.level <= 66) {
		user.role = 'Master II ★3'
	} else if (user.level <= 68) {
		user.role = 'Master II ★4'
	} else if (user.level <= 70) {
		user.role = 'Master II ★5'
	} else if (user.level <= 72) {
		user.role = 'Master III ★1'
	} else if (user.level <= 74) {
		user.role = 'Master III ★2'
	} else if (user.level <= 76) {
		user.role = 'Master III ★3'
	} else if (user.level <= 78) {
		user.role = 'Master III ★4'
	} else if (user.level <= 80) {
		user.role = 'Master III ★5'
	} else if (user.level <= 82) {
		user.role = 'Master IV ★1'
	} else if (user.level <= 84) {
		user.role = 'Master IV ★2'
	} else if (user.level <= 86) {
		user.role = 'Master IV ★3'
	} else if (user.level <= 88) {
		user.role = 'Master IV ★4'
	} else if (user.level <= 90) {
		user.role = 'Master IV ★5'
	} else if (user.level <= 92) {
		user.role = 'Master V ★1'
	} else if (user.level <= 94) {
		user.role = 'Master V ★2'
	} else if (user.level <= 96) {
		user.role = 'Master V ★3'
	} else if (user.level <= 98) {
		user.role = 'Master V ★4'
	} else if (user.level <= 100) {
		user.role = 'Master V ★5'
	} else if (user.level <= 102) {
		user.role = 'GranMaster I ★1'
	} else if (user.level <= 104) {
		user.role = 'GranMaster I ★2'
	} else if (user.level <= 106) {
		user.role = 'GranMaster I ★3'
	} else if (user.level <= 108) {
		user.role = 'GranMaster I ★4'
	} else if (user.level <= 110) {
		user.role = 'GranMaster I ★5'
	} else if (user.level <= 112) {
		user.role = 'GranMaster II ★1'
	} else if (user.level <= 114) {
		user.role = 'GranMaster II ★2'
	} else if (user.level <= 116) {
		user.role = 'GranMaster II ★3'
	} else if (user.level <= 118) {
		user.role = 'GranMaster II ★4'
	} else if (user.level <= 120) {
		user.role = 'GranMaster II ★5'
	} else if (user.level <= 122) {
		user.role = 'GranMaster III ★1'
	} else if (user.level <= 124) {
		user.role = 'GranMaster III ★2'
	} else if (user.level <= 126) {
		user.role = 'GranMaster III ★3'
	} else if (user.level <= 128) {
		user.role = 'GranMaster III ★4'
	} else if (user.level <= 130) {
		user.role = 'GranMaster III ★5'
	} else if (user.level <= 132) {
		user.role = 'GranMaster IV ★1'
	} else if (user.level <= 134) {
		user.role = 'GranMaster IV ★2'
	} else if (user.level <= 136) {
		user.role = 'GranMaster IV ★3'
	} else if (user.level <= 138) {
		user.role = 'GranMaster IV ★4'
	} else if (user.level <= 140) {
		user.role = 'GranMaster IV ★5'
	} else if (user.level <= 142) {
		user.role = 'GranMaster V ★1'
	} else if (user.level <= 144) {
		user.role = 'GranMaster V ★2'
	} else if (user.level <= 146) {
		user.role = 'GranMaster V ★3'
	} else if (user.level <= 148) {
		user.role = 'GranMaster V ★4'
	} else if (user.level <= 152) {
		user.role = 'GranMaster V ★5'
	} else if (user.level <= 154) {
		user.role = 'GranMaster VI ★1'
	} else if (user.level <= 156) {
		user.role = 'GranMaster VI ★2'
	} else if (user.level <= 158) {
		user.role = 'GranMaster VI ★3'
	} else if (user.level <= 160) {
		user.role = 'GranMaster VI ★4'
	} else if (user.level <= 162) {
		user.role = 'GranMaster VI ★5'
	} else if (user.level <= 102) {
		user.role = 'Epic I ★1'
	} else if (user.level <= 104) {
		user.role = 'Epic I ★2'
	} else if (user.level <= 106) {
		user.role = 'Epic I ★3'
	} else if (user.level <= 108) {
		user.role = 'Epic I ★4'
	} else if (user.level <= 110) {
		user.role = 'Epic I ★5'
	} else if (user.level <= 110) {
		user.role = 'Epic I ★6'
	} else if (user.level <= 112) {
		user.role = 'Epic II ★1'
	} else if (user.level <= 114) {
		user.role = 'Epic II ★2'
	} else if (user.level <= 116) {
		user.role = 'Epic II ★3'
	} else if (user.level <= 118) {
		user.role = 'Epic II ★4'
	} else if (user.level <= 120) {
		user.role = 'Epic II ★5'
	} else if (user.level <= 110) {
		user.role = 'Epic II ★6'
	} else if (user.level <= 122) {
		user.role = 'Epic III ★1'
	} else if (user.level <= 124) {
		user.role = 'Epic III ★2'
	} else if (user.level <= 126) {
		user.role = 'Epic III ★3'
	} else if (user.level <= 128) {
		user.role = 'Epic III ★4'
	} else if (user.level <= 130) {
		user.role = 'Epic III ★5'
	} else if (user.level <= 110) {
		user.role = 'Epic III ★6'
	} else if (user.level <= 132) {
		user.role = 'Epic IV ★1'
	} else if (user.level <= 134) {
		user.role = 'Epic IV ★2'
	} else if (user.level <= 136) {
		user.role = 'Epic IV ★3'
	} else if (user.level <= 138) {
		user.role = 'Epic IV ★4'
	} else if (user.level <= 140) {
		user.role = 'Epic IV ★5'
	} else if (user.level <= 110) {
		user.role = 'Epic IV ★6'
	} else if (user.level <= 142) {
		user.role = 'Epic V ★1'
	} else if (user.level <= 144) {
		user.role = 'Epic V ★2'
	} else if (user.level <= 146) {
		user.role = 'Epic V ★3'
	} else if (user.level <= 148) {
		user.role = 'Epic V ★4'
	} else if (user.level <= 152) {
		user.role = 'Epic V ★5'
	} else if (user.level <= 110) {
		user.role = 'Epic V ★6'
	} else if (user.level <= 154) {
		user.role = 'Epic VI ★1'
	} else if (user.level <= 156) {
		user.role = 'Epic VI ★2'
	} else if (user.level <= 158) {
		user.role = 'Epic VI ★3'
	} else if (user.level <= 160) {
		user.role = 'Epic VI ★4'
	} else if (user.level <= 162) {
		user.role = 'Epic VI ★5'
	} else if (user.level <= 110) {
		user.role = 'Epic VI ★6'
	} else if (user.level <= 174) {
		user.role = 'Legends I ★1'
	} else if (user.level <= 176) {
		user.role = 'Legends I ★2'
	} else if (user.level <= 178) {
		user.role = 'Legends I ★3'
	} else if (user.level <= 180) {
		user.role = 'Legends I ★4'
	} else if (user.level <= 182) {
		user.role = 'Legends I ★5'
	} else if (user.level <= 184) {
		user.role = 'Legends I ★6'
	} else if (user.level <= 186) {
		user.role = 'Legends II ★1'
	} else if (user.level <= 188) {
		user.role = 'Legends II ★2'
	} else if (user.level <= 190) {
		user.role = 'Legends II ★3'
	} else if (user.level <= 192) {
		user.role = 'Legends II ★4'
	} else if (user.level <= 194) {
		user.role = 'Legends II ★5'
	} else if (user.level <= 196) {
		user.role = 'Legends II ★6'
	} else if (user.level <= 198) {
		user.role = 'Legends III ★1'
	} else if (user.level <= 200) {
		user.role = 'Legends III ★2'
	} else if (user.level <= 210) {
		user.role = 'Legends III ★3'
	} else if (user.level <= 220) {
		user.role = 'Legends III ★4'
	} else if (user.level <= 230) {
		user.role = 'Legends III ★5'
	} else if (user.level <= 240) {
		user.role = 'Legends III ★6'
	} else if (user.level <= 250) {
		user.role = 'Legends IV ★1'
	} else if (user.level <= 260) {
		user.role = 'Legends IV ★2'
	} else if (user.level <= 270) {
		user.role = 'Legends IV ★3'
	} else if (user.level <= 280) {
		user.role = 'Legends IV ★4'
	} else if (user.level <= 290) {
		user.role = 'Legends IV ★5'
	} else if (user.level <= 300) {
		user.role = 'Legends IV ★6'
	} else if (user.level <= 310) {
		user.role = 'Legends V ★1'
	} else if (user.level <= 320) {
		user.role = 'Legends V ★2'
	} else if (user.level <= 330) {
		user.role = 'Legends V ★3'
	} else if (user.level <= 340) {
		user.role = 'Legends V ★4'
	} else if (user.level <= 350) {
		user.role = 'Legends V ★5'
	} else if (user.level <= 360) {
		user.role = 'Legends V ★6'
	} else if (user.level <= 370) {
		user.role = 'Legends VI ★1'
	} else if (user.level <= 380) {
		user.role = 'Legends VI ★2'
	} else if (user.level <= 390) {
		user.role = 'Legends VI ★3'
	} else if (user.level <= 400) {
		user.role = 'Legends VI ★4'
	} else if (user.level <= 410) {
		user.role = 'Legends VI ★5'
	} else if (user.level <= 420) {
		user.role = 'Legends VI ★6'
	} else if (user.level <= 430) {
		user.role = 'Mytic ★1'
	} else if (user.level <= 440) {
		user.role = 'Mytic ★2'
	} else if (user.level <= 450) {
		user.role = 'Mytic ★3'
	} else if (user.level <= 460) {
		user.role = 'Mytic ★4'
	} else if (user.level <= 470) {
		user.role = 'Mytic ★5'
	} else if (user.level <= 480) {
		user.role = 'Mytic ★6'
	} else if (user.level <= 490) {
		user.role = 'Mytic ★7'
	} else if (user.level <= 500) {
		user.role = 'Mytic ★8'
	} else if (user.level <= 600) {
		user.role = 'Mytic ★9'
	} else if (user.level <= 700) {
		user.role = 'Mytic ★10'
	} else if (user.level <= 800) {
		user.role = 'Mytic ★11'
	} else if (user.level <= 900) {
		user.role = 'Mytic ★12'
	} else if (user.level <= 1000) {
		user.role = 'Mytic ★13'
	} else if (user.level <= 1500) {
		user.role = 'Mytic ★14'
	} else if (user.level <= 2000) {
		user.role = 'Mytic ★15'
	} else if (user.level <= 2500) {
		user.role = 'Mytic ★16'
	} else if (user.level <= 3000) {
		user.role = 'Mytic ★17'
	} else if (user.level <= 3500) {
		user.role = 'Mytic ★18'
	} else if (user.level <= 7000) {
		user.role = 'Mytic ★19'
	} else if (user.level <= 8000) {
		user.role = 'Mytic ★20'
	} else if (user.level <= 9000) {
		user.role = 'Mytic ★21'
	} else if (user.level <= 10000) {
		user.role = 'Mytic ★22'
	} else if (user.level <= 10000) {
		user.role = 'Mytic ★23'
	} else if (user.level <= 10000) {
		user.role = 'Mytic ★24'
	} else if (user.level <= 10000) {
		user.role = 'Mytic ★25'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★26'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★27'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★28'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★29'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★30'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★31'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★32'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★33'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★34'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★35'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★36'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★37'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★38'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★39'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★40'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★41'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★42'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★43'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★44'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★45'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★46'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★47'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★48'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Honor ★49'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★50'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★51'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★52'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★53'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★54'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★55'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★56'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★57'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★58'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★59'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★60'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★61'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★62'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★63'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★64'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★65'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★66'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★67'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★68'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★69'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★70'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★71'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★72'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★73'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★74'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★75'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★76'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★77'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★78'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★79'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★80'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★81'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★82'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★83'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★84'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★85'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★86'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★87'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★88'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★89'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★90'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★91'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★92'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★93'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★94'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★95
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★96'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★97'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★98'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★99'
	} else if (user.level <= 10000) {
		user.role = 'Mytic Glory ★100
	} else if (user.level <= 10000) {
		user.role = 'Mytic Imortal ★100+'
	} 
        
		if (before !== user.level) {
			let name = user.name
			let chating = `乂  *L E V E L  U P*\n\n`
			chating += `┌  ◦ *Progress* : [ ${before} ] ➠ [ ${user.level} ]\n`
			chating += `└  ◦ *Unlocked* : ${user.role}\nKamu Akan Mendapatkan Premium Setika Level 100`
			chating += footer.trim()

			const rank = new canvacord.Rank()
            .setAvatar(pp)
            .setCurrentXP(curr)
            .setLevel(user.level, "RANK", true)
            .setRank(user.level, "LEVEL", true)
            .setLevelColor("#2B2E35", "#2B2E35")
            .setRankColor("#FFFFFF", "#6636E5")
            .setRequiredXP(xp)
            .setStatus("streaming")
            .setProgressBar("#6636E5", "COLOR")
            .setProgressBarTrack("#FFFFFF")
            .setUsername(user.name)
            .setDiscriminator(`0001`)
            .setFontSize(1.5)
        
            rank.build()
            .then(data => {
                conn.sendFile(m.chat, data, "RankCad.png", chating, m)
              })
           }
		}
	}